---

- hosts: all
  become: true
  pre_tasks:
      - name: Initialize the user defined variables
        set_fact:
            pgs17cis_install_postgresql: false
        tags:
            - always
  roles:
      - role: "{{ playbook_dir }}"
