---

- name: "PRELIM | Install and Start PostgreSQL"
  include_tasks: postgresql17_install.yml
  when: pgs17cis_install_postgresql

- name: "PRELIM | Install ACL when needed"
  ansible.builtin.package:
      name: acl
      state: present

- name: "PRELIM | Install crypto-policies"
  ansible.builtin.package:
      name: crypto-policies
      state: present

- name: "PRELIM | Get postgres config file path"
  ansible.builtin.shell: psql -U postgres -c 'SHOW config_file' | tail -n+3 | head -n 1 | cut -c2-
  changed_when: false
  failed_when: false
  become: true
  become_user: "{{ pgs17cis_pgs17_usr }}"
  register: pgs17cis_config_file_get

- name: "PRELIM | Get postgres config file path"
  ansible.builtin.shell: psql -U postgres -c 'SHOW hba_file' | tail -n+3 | head -n 1 | cut -c2-
  changed_when: false
  failed_when: false
  become_user: "{{ pgs17cis_pgs17_usr }}"
  register: pgs17cis_hba_config_file_get

- name: "PRELIM | Set variable for service name"
  ansible.builtin.set_fact:
      pgs17cis_postgresql_service_auto: "{{ (ansible_os_family == 'Debian') | ternary('postgresql', 'postgresql-17') }}"

- name: "PRELIM | 2.1 | Get postgresql user home folder"
  ansible.builtin.shell: "grep {{ pgs17cis_pgs17_usr }} /etc/passwd | cut -f6 -d:"
  changed_when: false
  failed_when: false
  register: pgs17cis_pgs17_usr_home_dir_get
  when:
      - pgs17cis_rule_2_1

- name: "PRELIM | Get postgresql share directory"
  ansible.builtin.shell: "{{ pgs17cis_pgspackage_bin_dir }}/pg_config --sharedir"
  changed_when: false
  failed_when: false
  register: pgs17cis_pgs17_sharedir_get

- name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA)"
  block:
      - name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA) | Get path"
        ansible.builtin.shell: psql -c 'show data_directory' | tail -n+3 | head -n 1 | cut -c2-
        check_mode: false
        changed_when: false
        register: pgs17cis_pgdata_cmd
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"

      - name: "PRELIM | Finding the PostgreSQL Configured Data Directory (PGDATA) | Make var easier to use"
        ansible.builtin.set_fact:
            pgs17cis_data_folder: "{{ pgs17cis_pgdata_cmd.stdout }}"
  when:
      - pgs17cis_rule_3_1_2

- name: "PRELIM | 6.7 | Check if /boot or /boot/efi reside on separate partitions"
  ansible.builtin.shell: df --output=target /boot | tail -n 1
  changed_when: false
  check_mode: false
  register: pgs17cis_prelim_boot_part
  when:
      - pgs17cis_rule_6_7

- name: "PRELIM | 6.7 | Check whether machine is UEFI-based"
  ansible.builtin.stat:
      path: /sys/firmware/efi
  register: pgs17cis_prelim_sys_firmware_efi
  when:
      - pgs17cis_rule_6_7

- name: "PRELIM | 6.11 | Install PostgreSQL contrib package"
  block:
      - name: "PRELIM | 6.11 | Install PostgreSQL contrib package"
        ansible.builtin.package:
            name: "{{ pgs17cis_pgspackage_prefix }}-contrib"
            state: present
        when: ansible_distribution_file_variety == 'RedHat'
  when:
      - pgs17cis_rule_6_11 | default(false)

- name: "PRELIM | 7.1 | Find replication user name"
  block:
      - name: "PRELIM | 7.1 | Find replication user name | Scan pg_hba conf"
        ansible.builtin.shell: "grep -E -e '^\\s*host.*\\sreplication\\s' {{ pgs17cis_data_folder }}/pg_hba.conf | awk '{ print $3 }' | grep -v all | sort -u"
        changed_when: false
        failed_when: false
        register: pgs17cis_prelim_hba_repusers

      - name: "PRELIM | 7.1 | Find replication user name | set_var"
        ansible.builtin.set_fact:
            pgs17cis_replication_user: "{{ pgs17cis_prelim_hba_repusers.stdout_lines[0] }}"
        when:
            - pgs17cis_prelim_hba_repusers.stdout_lines | length > 0
  when:
      - pgs17cis_rule_7_1 | default(false)
