# syntax=docker/dockerfile:1

ARG RHEL_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-init:9.7
FROM ${RHEL_BASE_IMAGE}

ARG ANSIBLE_CORE_VERSION=2.15.13
ENV container=oci

RUN dnf -y install \
      acl \
      ca-certificates \
      crypto-policies \
      glibc-langpack-en \
      openssl \
      procps-ng \
      python3 \
      python3-pip \
      sudo \
      which \
    && python3 -m pip install --no-cache-dir "ansible-core==${ANSIBLE_CORE_VERSION}" \
    && dnf clean all

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
