---

- name: "5.6 | PATCH | Ensure the PostgreSQL Passwordcheck Extension is enabled"
  block:
      - name: "5.6 | PATCH | Ensure the PostgreSQL Passwordcheck extension is enabled | Get current shared_preload_libraries"
        ansible.builtin.shell: "psql -t -c 'SHOW shared_preload_libraries' | head -1|cut -c2-"
        changed_when: false
        failed_when: false
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"
        register: pgs17cis_5_6_current_libraries

      - name: "5.6 | PATCH | Ensure the PostgreSQL Passwordcheck extension is enabled | Add shared preload library "
        ansible.builtin.set_fact:
            pgs17cis_5_6_shared_preload_libraries: '{{ pgs17cis_5_6_current_libraries.stdout }},"$libdir/passwordcheck"'
        when: pgs17cis_5_6_current_libraries.stdout | length > 1

      - name: "5.6 | PATCH | Ensure the PostgreSQL Passwordcheck extension is enabled | Add shared preload library "
        ansible.builtin.set_fact:
            pgs17cis_5_6_shared_preload_libraries: '"$libdir/passwordcheck"'
        when: pgs17cis_5_6_current_libraries.stdout | length < 1

      - name: "5.6 | PATCH | Ensure the PostgreSQL Passwordcheck extension is enabled | Alter system"
        ansible.builtin.shell: psql -c 'alter system set shared_preload_libraries = {{ pgs17cis_5_6_shared_preload_libraries }};'
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"
        notify: restart postgresql
        when: "'passwordcheck' not in pgs17cis_5_6_current_libraries.stdout"
  vars:
      warn_control_id: '5.6'
  when:
      - pgs17cis_rule_5_6
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - patch
      - rule_5.6
