---

- name: "5.2 | AUDIT | Ensure PostgreSQL is bound to an IP address"
  block:
      - name: "5.2 | AUDIT | Ensure PostgreSQL is bound to an IP address | Get listen_addresses"
        ansible.builtin.shell: "psql -t -c 'SHOW listen_addresses' | head -1|cut -c2-"
        changed_when: false
        failed_when: false
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"
        register: pgs17cis_5_2_show_listen_addresses

      - name: "5.2 | AUDIT | Ensure PostgreSQL is bound to an IP address | Check listen_addresses"
        ansible.builtin.debug:
            msg:
                - "Warning!! Ensure listen_addresses is limited. This is a manual task."
                - "Requested: '<ip address 1>, <ip address 2>, ...' Actual: '{{ pgs17cis_5_2_show_listen_addresses.stdout }}'"
        when:
            - "'*' in pgs17cis_5_2_show_listen_addresses.stdout or '0.0.0.0' in pgs17cis_5_2_show_listen_addresses.stdout"

      - name: "5.2 | AUDIT | Ensure PostgreSQL is bound to an IP address | Present"
        ansible.builtin.import_tasks: warning_facts.yml
        when:
            - "'*' in pgs17cis_5_2_show_listen_addresses.stdout or '0.0.0.0' in pgs17cis_5_2_show_listen_addresses.stdout"
  vars:
      warn_control_id: '5.2'
  when:
      - pgs17cis_rule_5_2
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_5.2
