---

# Section 7
# Replication
- name: "7.1 | AUDIT | Ensure a replication-only user is created and used for streaming replication"
  block:
      - name: "7.1 | AUDIT | Ensure a replication-only user is created and used for streaming replication | Create replication user"
        ansible.builtin.shell: psql -t -c "select rolname from pg_roles where rolreplication is true;" | sed -r '/^\s*$/d' | awk '{$1=$1};1'
        changed_when: false
        failed_when: false
        become_user: "{{ pgs17cis_pgs17_usr }}"
        register: pgs17cis_7_1_replication_users

      - name: "7.1 | AUDIT | Ensure a replication-only user is created and used for streaming replication | Print warning"
        ansible.builtin.debug:
            msg:
                - "Warning!! A replication-only user should be created and used for streaming replication. This is a manual task."
                - "Requested: '{{ pgs17cis_replication_user }}' Actual: '{{ pgs17cis_7_1_replication_users.stdout }}'"
        when: "pgs17cis_replication_user not in pgs17cis_7_1_replication_users.stdout"

      - name: "7.1 | AUDIT | Ensure a replication-only user is created and used for streaming replication | Present"
        ansible.builtin.import_tasks: warning_facts.yml
        when: "pgs17cis_replication_user not in pgs17cis_7_1_replication_users.stdout"
  vars:
      warn_control_id: '7.1'
  when:
      - pgs17cis_rule_7_1
  tags:
      - level1-postgresql
      - level1-postgresqlonlinux
      - audit
      - rule_7.1
