---

- name: "7.4 | AUDIT | Ensure WAL archiving is configured and functional"
  block:
      - name: "7.4 | AUDIT | Ensure WAL archiving is configured and functional | Get parameter archive_mode"
        ansible.builtin.shell: "psql -t -c 'SHOW archive_mode' | head -1|cut -c2-"
        changed_when: false
        failed_when: false
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"
        register: pgs17cis_7_4_show_archive_mode

      - name: "7.4 | AUDIT | Ensure WAL archiving is configured and functional | Get parameter archive_command"
        ansible.builtin.shell: "psql -t -c 'SHOW archive_command' | head -1|cut -c2-"
        changed_when: false
        failed_when: false
        become: true
        become_user: "{{ pgs17cis_pgs17_usr }}"
        register: pgs17cis_7_4_show_archive_command

      - name: "7.4 | AUDIT | Ensure WAL archiving is configured and functional | Print warning"
        ansible.builtin.debug:
            msg:
                - "Warning!! A replication-only user should be created and used for streaming replication. This is a manual task."
                - "Requested: archive_mode: (not off) Actual: '{{ pgs17cis_7_4_show_archive_mode.stdout }}'"
                - "Requested: archive_command: (some command) Actual: '{{ pgs17cis_7_4_show_archive_command.stdout }}'"
        when:
            - "'off' in pgs17cis_7_4_show_archive_mode.stdout or pgs17cis_7_4_show_archive_command.stdout | length < 1 or 'true' in pgs17cis_7_4_show_archive_command.stdout"

      - name: "7.4 | AUDIT | Ensure WAL archiving is configured and functional | Present"
        ansible.builtin.import_tasks: warning_facts.yml
        when:
            - "'off' in pgs17cis_7_4_show_archive_mode.stdout or pgs17cis_7_4_show_archive_command.stdout | length < 1 or 'true' in pgs17cis_7_4_show_archive_command.stdout"
  vars:
      warn_control_id: '7.4'
  when:
      - pgs17cis_rule_7_4
  tags:
      - level1-postgresqlonlinux
      - audit
      - rule_7.4
