---

- name: restart postgresql
  ansible.builtin.service:
      name: "{{ pgs17cis_postgresql_service }}"
      state: restarted

- name: reboot system
  ansible.builtin.shell: sleep 3; reboot
  async: 15
  poll: 0
