---

# Section 2
- name: "2.4 | AUDIT | Ensure passwords are not stored in the service file"
  block:
      - name: "2.4 | AUDIT | Ensure passwords are not stored in the service file | Find all .pg_service.conf"
        ansible.builtin.shell: "find / -name .pg_service.conf -type f -print | xargs grep -H password"
        changed_when: false
        failed_when: false
        register: pgs17cis_2_4_pgservice_conf_pwd

      - name: "2.4 | AUDIT | Ensure passwords are not stored in the service file | PGSERVICEFILE"
        ansible.builtin.shell: 'test -z "$PGSERVICEFILE" || grep -H password "$PGSERVICEFILE"'
        changed_when: false
        failed_when: false
        register: pgs17cis_2_4_pgservicefile_pwd

      - name: "2.4 | AUDIT | Ensure passwords are not stored in the service file | PGSYSCONFDIR/pg_service.conf"
        ansible.builtin.shell: 'test -z "$PGSYSCONFDIR/pg_service.conf" || grep -H password "$PGSYSCONFDIR/pg_service.conf"'
        changed_when: false
        failed_when: false
        register: pgs17cis_2_4_pgsysconfdir_pwd

      - name: "2.4 | AUDIT | Ensure passwords are not stored in the service file | Show matching files"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the enabled repo's. Please review to confirm these are authorized repositories. This is a manual task."
                - "{{ pgs17cis_2_4_pgservice_conf_pwd.stdout_lines }}"
                - "{{ pgs17cis_2_4_pgservicefile_pwd.stdout_lines }}"
                - "{{ pgs17cis_2_4_pgsysconfdir_pwd.stdout_lines }}"
        when:
            - pgs17cis_2_4_pgservice_conf_pwd.stdout_lines | length > 0
            - pgs17cis_2_4_pgservicefile_pwd.stdout_lines | length > 0
            - pgs17cis_2_4_pgsysconfdir_pwd.stdout_lines | length > 0

      - name: "2.4 | AUDIT | Ensure passwords are not stored in the service file | Present"
        ansible.builtin.import_tasks: warning_facts.yml
        when:
            - pgs17cis_2_4_pgservice_conf_pwd.stdout_lines | length > 0
            - pgs17cis_2_4_pgservicefile_pwd.stdout_lines | length > 0
            - pgs17cis_2_4_pgsysconfdir_pwd.stdout_lines | length > 0
  vars:
      warn_control_id: '2.4'
  when:
      - pgs17cis_rule_2_4
  tags:
      - level1-postgresql
      - audit
      - rule_2.4
