---

- name: "1.3 | PATCH | Ensure systemd Service Files Are Enabled"
  ansible.builtin.service:
      name: "{{ pgs17cis_postgresql_service }}"
      enabled: true
  when:
      - pgs17cis_rule_1_3
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_1.3
