---

# Section 4
# User Access and Authorization
- name: "4.1 | PATCH | Ensure interactive login is disabled"
  block:
      - name: "4.1 | PATCH | Ensure interactive login is disabled | Get postgres account locked status"
        ansible.builtin.shell: "grep '^postgres:!' /etc/shadow"
        changed_when: false
        failed_when: false
        register: pgs17cis_4_1_postgres_shadow_account

      - name: "4.1 | PATCH | Ensure interactive login is disabled | Lock postgres account"
        ansible.builtin.shell: "passwd -l postgres"
        when: pgs17cis_4_1_postgres_shadow_account.stdout_lines | default([]) | count != 1
  when:
      - pgs17cis_rule_4_1
  tags:
      - level1-postgresqlonlinux
      - patch
      - rule_4.1
